#pragma once
#include <array>
#include <string_view>
namespace dm {
inline constexpr std::array<std::string_view, 200> featureIds = {
    "drive",
    "chorus",
    "delay",
    "reverb",
    "width",
    "hpf",
    "lpf",
    "trem",
    "pan",
    "flanger",
    "phaser",
    "crush",
    "vibrato",
    "slap",
    "phone",
    "tape",
    "stutter",
    "formant",
    "plate",
    "comb",
    "glue",
    "warm",
    "predelay",
    "fadeout",
    "grain",
    "melt",
    "worm",
    "rot",
    "infection",
    "crawl",
    "air",
    "grit",
    "haze",
    "bite",
    "vortex",
    "seance",
    "ripple",
    "halo",
    "pulse",
    "fog",
    "needle",
    "ink",
    "loud",
    "softclip",
    "tilt",
    "basshelf",
    "airshelf",
    "presence",
    "mud",
    "debox",
    "notch",
    "widen",
    "monobass",
    "room",
    "hall",
    "exciter",
    "warmth",
    "satin",
    "duck",
    "shimmer",
    "chorusbus",
    "focus",
    "trim",
    "balance",
    "sheen",
    "softsat",
    "edge",
    "bloom",
    "swirl",
    "ping",
    "drift",
    "snap",
    "body",
    "airlift",
    "subboost",
    "notchv",
    "ringmod",
    "deepphase",
    "longecho",
    "freeze",
    "vinyl",
    "radio",
    "under",
    "glass",
    "pulseamp",
    "swirlpan",
    "cream",
    "fogbank",
    "glue2",
    "ceiling",
    "busdrive",
    "airmax",
    "lowend",
    "midcarve",
    "widen2",
    "mono80",
    "polishlp",
    "polishhp",
    "sparkle",
    "velvet",
    "punch",
    "silk",
    "mass",
    "polishverb",
    "image",
    "finalloud",
    "curve",
    "clean",
    "stage",
    "wire",
    "glue3",
    "shelfmaster",
    "finaltrim",
    "sublift",
    "presence2",
    "mudnotch",
    "boxnotch",
    "nightair",
    "sleepgate",
    "redroom",
    "acidbite",
    "ghostdelay",
    "boneeq",
    "marrow",
    "cinder",
    "ashshelf",
    "cobalt",
    "ember",
    "lilac",
    "pine",
    "inkdrip",
    "needle2",
    "halo2",
    "ripple2",
    "orbit",
    "choirbed",
    "pluckslap",
    "drumglue",
    "bassfocus",
    "hatair",
    "snapsat",
    "roomtap",
    "darkhall",
    "brightplate",
    "slowflange",
    "fasttrem",
    "widechorus",
    "tightcomp",
    "opencomp",
    "deess",
    "lowmono",
    "sideair",
    "crush2",
    "wow2",
    "flutter",
    "gate16",
    "reverse",
    "octdown",
    "octup",
    "resonant",
    "smear",
    "dust",
    "tape2",
    "limiter2",
    "clip2",
    "air2",
    "width3",
    "hall2",
    "room2",
    "delay2",
    "phaser2",
    "chorus2",
    "vibrato2",
    "pan2",
    "trem2",
    "lpf2",
    "hpf2",
    "drive2",
    "grit2",
    "haze2",
    "rot2",
    "melt2",
    "worm2",
    "infection2",
    "crawl2",
    "star2",
    "tower2",
    "vortex2",
    "seance2",
    "fog2",
    "ink2",
    "needle3",
    "halo3",
    "pulse2",
    "ripple3",
    "orbit2",
    "choir2",
    "plate2",
    "comb2",
    "formant2",
};
inline constexpr std::array<std::string_view, 200> featureNames = {
    "Drive",
    "Doubler / Chorus",
    "Delay",
    "Reverb",
    "Stereo Width",
    "High-Pass",
    "Low-Pass",
    "Tremolo / Chop",
    "Auto-Pan",
    "Flanger",
    "Phaser",
    "Bitcrush / Lofi",
    "Vibrato",
    "Slapback",
    "Telephone",
    "Tape / Wow",
    "Stutter / Gate",
    "Formant Body",
    "Short Plate",
    "Interval Comb",
    "Mid Glue",
    "Warmth",
    "Predelay",
    "Fade / Shape",
    "Grain Scramble",
    "Melt",
    "Worm / Wriggle",
    "Rot",
    "Infection Echo",
    "Crawl Trail",
    "Star Air",
    "Devil Grit",
    "Moon Haze",
    "Tower Bite",
    "Vortex Orbit",
    "Seance Choir",
    "Ripple Spray",
    "Halo Bloom",
    "Euclid Pulse",
    "Fog Bank",
    "Needle Wow",
    "Draw Ink",
    "Loud / Limiter",
    "Soft Clip",
    "Tilt EQ",
    "Bass Shelf",
    "Air Shelf",
    "Presence",
    "Mud Cut",
    "Box Cut",
    "Hum Notch",
    "Haas Width",
    "Mono Bass",
    "Short Room",
    "Hall",
    "Exciter",
    "Warmth 2",
    "Satin Roll",
    "Polish Pump",
    "Shimmer",
    "Bus Chorus",
    "Focus",
    "Trim",
    "Balance",
    "Sheen",
    "Soft Sat",
    "Edge",
    "Bloom",
    "Swirl Filter",
    "Ping",
    "Drift",
    "Snap",
    "Body",
    "Air Lift",
    "Sub Boost",
    "Notch Sweep",
    "Ring Light",
    "Deep Phase",
    "Long Echo",
    "Freeze",
    "Vinyl",
    "Radio",
    "Underwater",
    "Glass",
    "Pulse Amp",
    "Swirl Pan",
    "Cream",
    "Fog Bank 2",
    "Glue II",
    "Ceiling",
    "Bus Drive",
    "Air Max",
    "Low End",
    "Mid Carve",
    "Widen II",
    "Mono 80",
    "Polish LP",
    "Polish HP",
    "Sparkle",
    "Velvet",
    "Punch",
    "Silk",
    "Mass",
    "Polish Verb",
    "Image",
    "Final Loud",
    "Curve",
    "Clean",
    "Stage",
    "Wire",
    "Parallel Glue",
    "Shelf Master",
    "Final Trim",
    "Sub Lift",
    "Presence Peak",
    "Mud Notch",
    "Box Notch",
    "Night Air",
    "Sleep Gate",
    "Red Room",
    "Acid Bite",
    "Ghost Delay",
    "Bone EQ",
    "Marrow",
    "Cinder",
    "Ash Shelf",
    "Cobalt",
    "Ember",
    "Lilac Halo",
    "Pine Room",
    "Ink Drip",
    "Needle Flutter",
    "Halo II",
    "Ripple II",
    "Orbit",
    "Choir Bed",
    "Pluck Slap",
    "Drum Glue",
    "Bass Focus",
    "Hat Air",
    "Snap Sat",
    "Room Tap",
    "Dark Hall",
    "Bright Plate",
    "Slow Flange",
    "Fast Trem",
    "Wide Chorus",
    "Tight Comp",
    "Open Comp",
    "De-ess",
    "Low Mono",
    "Side Air",
    "Crush II",
    "Wow II",
    "Flutter",
    "16th Gate",
    "Reverse Bloom",
    "Oct Down",
    "Oct Up",
    "Resonant",
    "Smear",
    "Dust",
    "Tape II",
    "Limiter II",
    "Clip II",
    "Air II",
    "Width III",
    "Hall II",
    "Room II",
    "Delay II",
    "Phaser II",
    "Chorus II",
    "Vibrato II",
    "Pan II",
    "Trem II",
    "Low-Pass II",
    "High-Pass II",
    "Drive II",
    "Grit II",
    "Haze II",
    "Rot II",
    "Melt II",
    "Worm II",
    "Infection II",
    "Crawl II",
    "Star II",
    "Tower II",
    "Vortex II",
    "Seance II",
    "Fog II",
    "Ink II",
    "Needle III",
    "Halo III",
    "Pulse II",
    "Ripple III",
    "Orbit II",
    "Choir II",
    "Plate II",
    "Comb II",
    "Formant II",
};
} // namespace dm
