#pragma once
#include <cstddef>
namespace kt {
struct FxDef { const char* id; const char* name; int family; };

// Family indices used by DSP + UI category browser.
// 0 Delay - 1 Reverb - 2 Stereo - 3 Modulation - 4 Filter/EQ - 5 Drive - 6 Dynamics - 7 Character
inline constexpr const char* kFxFamilyNames[] = {
    "Delay", "Reverb", "Stereo", "Modulation", "Filter / EQ", "Drive", "Dynamics", "Character"
};
inline constexpr int kFxFamilyCount = 8;

inline const char* fxFamilyName(int family)
{
    if (family >= 0 && family < kFxFamilyCount) return kFxFamilyNames[family];
    return "Other";
}

inline constexpr FxDef kFx[] = {
    { "drive", "Drive", 5 },
    { "chorus", "Doubler / Chorus", 3 },
    { "delay", "Delay", 0 },
    { "reverb", "Reverb", 1 },
    { "width", "Stereo Width", 2 },
    { "hpf", "High-Pass", 4 },
    { "lpf", "Low-Pass", 4 },
    { "trem", "Tremolo / Chop", 3 },
    { "pan", "Auto-Pan", 2 },
    { "flanger", "Flanger", 3 },
    { "phaser", "Phaser", 3 },
    { "crush", "Bitcrush / Lofi", 5 },
    { "vibrato", "Vibrato", 3 },
    { "slap", "Slapback", 0 },
    { "phone", "Telephone", 4 },
    { "tape", "Tape / Wow", 0 },
    { "stutter", "Stutter / Gate", 7 },
    { "formant", "Formant Body", 4 },
    { "plate", "Short Plate", 1 },
    { "comb", "Interval Comb", 7 },
    { "glue", "Mid Glue", 6 },
    { "warm", "Warmth", 5 },
    { "predelay", "Predelay", 0 },
    { "fadeout", "Fade / Shape", 6 },
    { "grain", "Grain Scramble", 7 },
    { "melt", "Melt", 3 },
    { "worm", "Worm / Wriggle", 3 },
    { "rot", "Rot", 3 },
    { "infection", "Infection Echo", 7 },
    { "crawl", "Crawl Trail", 7 },
    { "air", "Star Air", 4 },
    { "grit", "Devil Grit", 5 },
    { "haze", "Moon Haze", 7 },
    { "bite", "Tower Bite", 5 },
    { "vortex", "Vortex Orbit", 3 },
    { "seance", "Seance Choir", 7 },
    { "ripple", "Ripple Spray", 3 },
    { "halo", "Halo Bloom", 3 },
    { "pulse", "Euclid Pulse", 3 },
    { "fog", "Fog Bank", 7 },
    { "needle", "Needle Wow", 7 },
    { "ink", "Draw Ink", 7 },
    { "loud", "Loud / Limiter", 6 },
    { "softclip", "Soft Clip", 5 },
    { "tilt", "Tilt EQ", 4 },
    { "basshelf", "Bass Shelf", 4 },
    { "airshelf", "Air Shelf", 4 },
    { "presence", "Presence", 4 },
    { "mud", "Mud Cut", 7 },
    { "debox", "Box Cut", 7 },
    { "notch", "Hum Notch", 4 },
    { "widen", "Haas Width", 2 },
    { "monobass", "Mono Bass", 2 },
    { "room", "Short Room", 1 },
    { "hall", "Hall", 1 },
    { "exciter", "Exciter", 7 },
    { "warmth", "Warmth 2", 5 },
    { "satin", "Satin Roll", 5 },
    { "duck", "Polish Pump", 6 },
    { "shimmer", "Shimmer", 1 },
    { "chorusbus", "Bus Chorus", 3 },
    { "focus", "Focus", 4 },
    { "trim", "Trim", 6 },
    { "balance", "Balance", 2 },
    { "sheen", "Sheen", 7 },
    { "softsat", "Soft Sat", 5 },
    { "edge", "Edge", 7 },
    { "bloom", "Bloom", 7 },
    { "swirl", "Swirl Filter", 3 },
    { "ping", "Ping", 0 },
    { "drift", "Drift", 3 },
    { "snap", "Snap", 7 },
    { "body", "Body", 7 },
    { "airlift", "Air Lift", 4 },
    { "subboost", "Sub Boost", 7 },
    { "notchv", "Notch Sweep", 4 },
    { "ringmod", "Ring Light", 3 },
    { "deepphase", "Deep Phase", 3 },
    { "longecho", "Long Echo", 0 },
    { "freeze", "Freeze", 1 },
    { "vinyl", "Vinyl", 5 },
    { "radio", "Radio", 4 },
    { "under", "Underwater", 4 },
    { "glass", "Glass", 5 },
    { "pulseamp", "Pulse Amp", 3 },
    { "swirlpan", "Swirl Pan", 2 },
    { "cream", "Cream", 5 },
    { "fogbank", "Fog Bank 2", 7 },
    { "glue2", "Glue II", 6 },
    { "ceiling", "Ceiling", 6 },
    { "busdrive", "Bus Drive", 5 },
    { "airmax", "Air Max", 4 },
    { "lowend", "Low End", 7 },
    { "midcarve", "Mid Carve", 7 },
    { "widen2", "Widen II", 2 },
    { "mono80", "Mono 80", 2 },
    { "polishlp", "Polish LP", 5 },
    { "polishhp", "Polish HP", 5 },
    { "sparkle", "Sparkle", 7 },
    { "velvet", "Velvet", 5 },
    { "punch", "Punch", 6 },
    { "silk", "Silk", 5 },
    { "mass", "Mass", 7 },
    { "polishverb", "Polish Verb", 5 },
    { "image", "Image", 2 },
    { "finalloud", "Final Loud", 6 },
    { "curve", "Curve", 7 },
    { "clean", "Clean", 6 },
    { "stage", "Stage", 2 },
    { "wire", "Wire", 4 },
    { "glue3", "Parallel Glue", 6 },
    { "shelfmaster", "Shelf Master", 4 },
    { "finaltrim", "Final Trim", 6 },
    { "sublift", "Sub Lift", 7 },
    { "presence2", "Presence Peak", 4 },
    { "mudnotch", "Mud Notch", 4 },
    { "boxnotch", "Box Notch", 4 },
    { "nightair", "Night Air", 4 },
    { "sleepgate", "Sleep Gate", 6 },
    { "redroom", "Red Room", 1 },
    { "acidbite", "Acid Bite", 5 },
    { "ghostdelay", "Ghost Delay", 0 },
    { "boneeq", "Bone EQ", 4 },
    { "marrow", "Marrow", 7 },
    { "cinder", "Cinder", 5 },
    { "ashshelf", "Ash Shelf", 4 },
    { "cobalt", "Cobalt", 7 },
    { "ember", "Ember", 5 },
    { "lilac", "Lilac Halo", 7 },
    { "pine", "Pine Room", 7 },
    { "inkdrip", "Ink Drip", 7 },
    { "needle2", "Needle Flutter", 7 },
    { "halo2", "Halo II", 3 },
    { "ripple2", "Ripple II", 3 },
    { "orbit", "Orbit", 3 },
    { "choirbed", "Choir Bed", 1 },
    { "pluckslap", "Pluck Slap", 0 },
    { "drumglue", "Drum Glue", 6 },
    { "bassfocus", "Bass Focus", 4 },
    { "hatair", "Hat Air", 4 },
    { "snapsat", "Snap Sat", 5 },
    { "roomtap", "Room Tap", 0 },
    { "darkhall", "Dark Hall", 1 },
    { "brightplate", "Bright Plate", 1 },
    { "slowflange", "Slow Flange", 3 },
    { "fasttrem", "Fast Trem", 3 },
    { "widechorus", "Wide Chorus", 0 },
    { "tightcomp", "Tight Comp", 6 },
    { "opencomp", "Open Comp", 6 },
    { "deess", "De-ess", 4 },
    { "lowmono", "Low Mono", 2 },
    { "sideair", "Side Air", 2 },
    { "crush2", "Crush II", 5 },
    { "wow2", "Wow II", 3 },
    { "flutter", "Flutter", 3 },
    { "gate16", "16th Gate", 6 },
    { "reverse", "Shimmer Bloom", 7 },
    { "octdown", "Low Ring Mod", 7 },
    { "octup", "High Ring Mod", 7 },
    { "resonant", "Resonant", 4 },
    { "smear", "Smear", 7 },
    { "dust", "Dust", 5 },
    { "tape2", "Tape II", 0 },
    { "limiter2", "Limiter II", 6 },
    { "clip2", "Clip II", 5 },
    { "air2", "Air II", 4 },
    { "width3", "Width III", 2 },
    { "hall2", "Hall II", 1 },
    { "room2", "Room II", 1 },
    { "delay2", "Delay II", 0 },
    { "phaser2", "Phaser II", 3 },
    { "chorus2", "Chorus II", 3 },
    { "vibrato2", "Vibrato II", 3 },
    { "pan2", "Pan II", 2 },
    { "trem2", "Trem II", 3 },
    { "lpf2", "Low-Pass II", 4 },
    { "hpf2", "High-Pass II", 4 },
    { "drive2", "Drive II", 5 },
    { "grit2", "Grit II", 5 },
    { "haze2", "Haze II", 7 },
    { "rot2", "Rot II", 3 },
    { "melt2", "Melt II", 3 },
    { "worm2", "Worm II", 3 },
    { "infection2", "Infection II", 7 },
    { "crawl2", "Crawl II", 7 },
    { "star2", "Star II", 7 },
    { "tower2", "Tower II", 7 },
    { "vortex2", "Vortex II", 3 },
    { "seance2", "Seance II", 7 },
    { "fog2", "Fog II", 7 },
    { "ink2", "Ink II", 7 },
    { "needle3", "Needle III", 7 },
    { "halo3", "Halo III", 3 },
    { "pulse2", "Pulse II", 3 },
    { "ripple3", "Ripple III", 3 },
    { "orbit2", "Orbit II", 3 },
    { "choir2", "Choir II", 1 },
    { "plate2", "Plate II", 1 },
    { "comb2", "Comb II", 7 },
    { "formant2", "Formant II", 4 },
};
inline constexpr int kFxCount = 200;
static_assert(sizeof(kFx) / sizeof(kFx[0]) == 200, "fx count");
}
